<div class="academic-area pt-100 pb-70">
            <div class="container">
                <div class="section-title">
                    <h2>Academics</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipiscing elit ut elit tellus luctus nec ullamcorper mattis </p>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="200" data-aos-once="true">
                        <div class="single-academics-card">
                            <div class="academic-top-content">
                                <i class="flaticon-college-graduation"></i>
                                <a href="academics-details.html"><h3>Undergraduate Education</h3></a>
                            </div>
                            <p>Lorem ipsum dolor sit amet consectetur ad
                            piscing elit ut elit tellus luctus nec dolor sit amet consec teturul</p>
                            <a href="academics-details.html" class="read-more-btn">Undergraduate Education<i class="flaticon-next"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="400" data-aos-once="true">
                        <div class="single-academics-card">
                            <div class="academic-top-content">
                                <i class="flaticon-graduation"></i>
                                <a href="academics-details.html"><h3>Graduate Education</h3></a>
                            </div>
                            <p>Lorem ipsum dolor sit amet consectetur ad
                            piscing elit ut elit tellus luctus nec dolor sit amet consec teturul</p>
                            <a href="academics-details.html" class="read-more-btn">Graduate Education<i class="flaticon-next"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="600" data-aos-once="true">
                        <div class="single-academics-card">
                            <div class="academic-top-content">
                                <i class="flaticon-writing-tool"></i>
                                <a href="academics-details.html"><h3>Lifelong learning</h3></a>
                            </div>
                            <p>Lorem ipsum dolor sit amet consectetur ad
                            piscing elit ut elit tellus luctus nec dolor sit amet consec teturul</p>
                            <a href="academics-details.html" class="read-more-btn">Lifelong learning<i class="flaticon-next"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>