<div class="admisssion-area bg-f4f6f9 ptb-100">
            <div class="container">
                <div class="admission-content">
                    <div class="section-title">
                        <h2>Sanu Admission</h2>
                        <p>Lorem ipsum dolor sit amet consectetur adipiscing elit ut elit tellus luctus nec ullamcorper mattis </p>
                    </div>
                    <div class="admission-image">
                        <img src="assets/images/admission/admission-1.jpg" alt="Image">
                        <div class="icon">
                            <a class="popup-youtube play-btn" href="https://www.youtube.com/watch?v=6WQCJx_vEX4"><i class="ri-play-fill"></i></a>
                        </div>
                    </div>
                    <div class="query text-center">
                        <p>If You Have Any Query or Facing any Problem Please Contact Us Via Email</p>
                        <a href="admission.html" class="default-btn btn">More on admission<i class="flaticon-next"></i></a>
                    </div>
                </div>
            </div>
        </div>