<div class="banner-area pb-100">
            <div class="container-fluid">
                <div class="hero-slider owl-carousel owl-theme" data-slider-id="1">
                    <div class="slider-item banner-bg-1">
                        <div class="slider-content">
                            <h1>Explore Your Potential & Talents In Sanu</h1>
                            <p>Lorem ipsum dolor sit amet consectetur adipiscing elit. Ut elit tellus luctus nec ullamcorper mattis pulvinar dapibus dolor sit amet consec</p>
                            <a href="courses.html" class="default-btn btn">Start a Journey <i class="flaticon-next"></i></a>
                        </div>
                    </div>
                    <div class="slider-item banner-bg-2">
                        <div class="slider-content">
                            <h1>Explore Your Creativity & Talent With Sanu</h1>
                            <p>Lorem ipsum dolor sit amet consectetur adipiscing elit. Ut elit tellus luctus nec ullamcorper mattis pulvinar dapibus dolor sit amet consec</p>
                            <a href="courses.html" class="default-btn btn">Start a Journey <i class="flaticon-next"></i></a>
                        </div>
                    </div>
                    <div class="slider-item banner-bg-3">
                        <div class="slider-content">
                            <h1>Start Your Beautiful & Bright Future From Here</h1>
                            <p>Lorem ipsum dolor sit amet consectetur adipiscing elit. Ut elit tellus luctus nec ullamcorper mattis pulvinar dapibus dolor sit amet consec</p>
                            <a href="courses.html" class="default-btn btn">Start a Journey <i class="flaticon-next"></i></a>
                        </div>
                    </div>
                </div>
                <div class="owl-thumbs" data-slider-id="1">
                    <button class="owl-thumb-item">
                        <img src="assets/images/banner/thumb-1.jpg" alt="Images">  
                    </button>

                    <button class="owl-thumb-item">
                        <img src="assets/images/banner/thumb-2.jpg" alt="Images">  
                    </button>

                    <button class="owl-thumb-item">
                        <img src="assets/images/banner/thumb-3.jpg" alt="Images">  
                    </button>
                </div>
            </div>
        </div>