<div class="campus-life-area ptb-100">
            <div class="container">
                <div class="section-title">
                    <h2>Campus Life</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipiscing elit ut elit tellus luctus nec ullamcorper mattis </p>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="200" data-aos-once="true">
                        <div class="single-campus-card">
                            <div class="img">
                                <a href="campus-life.html"><img src="assets/images/campus-life/campus-life-1.jpg" alt="Image"></a>
                            </div>
                            <div class="campus-content">
                                <span>Art & Culture</span>
                                <a href="campus-life.html"><h3>Art, Exercise And Escapism In Nature</h3></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="400" data-aos-once="true">
                        <div class="single-campus-card">
                            <div class="img">
                                <a href="campus-life.html"><img src="assets/images/campus-life/campus-life-2.jpg" alt="Image"></a>
                            </div>
                            <div class="campus-content">
                                <span>Athletics & Fitness</span>
                                <a href="campus-life.html"><h3>Improve Athletic Performance Tips From Sanu</h3></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="600" data-aos-once="true">
                        <div class="single-campus-card">
                            <div class="img">
                                <a href="campus-life.html"><img src="assets/images/campus-life/campus-life-3.jpg" alt="Image"></a>
                            </div>
                            <div class="campus-content">
                                <span>Student Life</span>
                                <a href="campus-life.html"><h3>Why I Changed My Mind About Career Connections</h3></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="more-campus text-center">
                    <p>Select From Hundreds of Options. <a href="campus-life.html" class="read-more-btn active">More on Campus Life <i class="flaticon-next"></i></a></p>
                </div>
            </div>
        </div>