<div class="campus-information-area pb-70">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6" data-aos="fade-right" 
                    data-aos-easing="ease-in-sine" data-aos-duration="1300" data-aos-once="true">
                        <div class="campus-content pr-20">
                            <div class="campus-title">
                                <h2>Campus Information</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tem incid idunt ut labore et dolore magna aliqua. Ut enim ad minim ven iam quis nostrud xerci tation ulla mco laboris nisi ut </p>
                            </div>
                            <div class="list">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <ul>
                                            <li>
                                                <i class="ri-check-fill"></i>
                                                <p>Graduate Programs</p>
                                            </li>
                                            <li>
                                                <i class="ri-check-fill"></i>
                                                <p>Programs</p>
                                            </li>
                                            <li>
                                                <i class="ri-check-fill"></i>
                                                <p>Doctoral Degrees</p>
                                            </li>
                                            <li>
                                                <i class="ri-check-fill"></i>
                                                <p>Alumni & Giving</p>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <ul>
                                            <li>
                                                <i class="ri-check-fill"></i>
                                                <p>Undergraduate</p>
                                            </li>
                                            <li>
                                                <i class="ri-check-fill"></i>
                                                <p>International Hubs</p>
                                            </li>
                                            <li>
                                                <i class="ri-check-fill"></i>
                                                <p>Doctoral Degrees</p>
                                            </li>
                                            <li>
                                                <i class="ri-check-fill"></i>
                                                <p>Global Students</p>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="counter">
                                <div class="row">
                                    <div class="col-lg-4 col-4">
                                        <div class="counter-card">
                                            <h1>
                                                <span class="odometer" data-count="65">00</span>
                                                <span class="target">+</span>
                                            </h1>
                                            <p>Years Of Experience</p>
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-4">
                                        <div class="counter-card">
                                            <h1>
                                                <span class="odometer" data-count="30">00</span>
                                                <span class="target heading-color">k</span><span class="target">+</span>
                                            </h1>
                                            <p>Global Students</p>
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-4">
                                        <div class="counter-card">
                                            <h1>
                                                <span class="odometer" data-count="52">00</span>
                                                <span class="target">+</span>
                                            </h1>
                                            <p>Student Nationalities</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a href="campus-life.html" class="default-btn btn">Start your application<i class="flaticon-next"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-6" data-aos="fade-up" 
                    data-aos-easing="ease-in-sine" data-aos-duration="1300" data-aos-once="true">
                        <div class="campus-image pl-20">
                            <img src="assets/images/campus-information/campus-1.jpg" alt="Image">
                        </div>
                    </div>
                </div>
            </div>
        </div>