<!--Start Contact Us Area-->        
<div class="contact-us-area pt-100 pb-70" style="background: grey">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="contacts-form">
                            <h3>Locate Us</h3>
                            <form id="contactForm">
                                <div class="row">
                                    <div class="col-lg-12 col-sm-12">
                                        <iframe src="<?=$map?>" width="100%" height="500" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="contact-and-address">
                            <h2>Need help?</h2>
                            <p>Get in touch with us.</p>
                            <div class="contact-and-address-content">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <div class="contact-card">
                                            <div class="icon">
                                                <i class="ri-phone-line"></i>
                                            </div>
                                            <h4>Call us on</h4>
                                            <p>Mobile: <a href="<?php ?>"><?php  ?></a><br></p>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <div class="contact-card">
                                            <div class="icon">
                                                <i class="ri-mail-send-line"></i>
                                            </div>
                                            <h4>Email us at</h4>
                                            <p>Mail: <a href="mailto:<?php  ?>"><?php ?></a></p>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <div class="contact-card">
                                            <div class="icon">
                                                <i class="ri-global-line"></i>
                                            </div>
                                            <h4>Our Website</h4>
                                            <p>Website: <?php ?></p>
                                            <br />
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <div class="contact-card">
                                            <div class="icon">
                                                <i class="ri-map-pin-line"></i>
                                            </div>
                                            <h4>Address</h4>
                                            <p><?php  ?></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
        <!--End Contact Us Area-->