<div class="copyright-area">
			            <div class="container">
			                <div class="copyright">
			                    <div class="row">
			                        <div class="col-lg-6 col-md-4">
			                           <!-- <div class="social-content">
			                                <ul>
			                                    <li><span>Follow Us On</span></li>
			                                    <li>
			                                        <a href="#" target="_blank"><i class="ri-facebook-fill"></i></a>
			                                    </li>
			                                    <li>
			                                        <a href="#" target="_blank"><i class="ri-twitter-fill"></i></a>
			                                    </li>
			                                    <li>
			                                        <a href="#" target="_blank"><i class="ri-instagram-line"></i></a>
			                                    </li>
			                                    <li>
			                                        <a href="#" target="_blank"><i class="ri-linkedin-fill"></i></a>
			                                    </li>
			                                </ul>
			                            </div> -->
			                        </div>
			                        <div class="col-lg-6 col-md-8">
			                            <div class="copy">
			                                <p>Proudly Powered by <a href="https://iaiict.abu.edu.ng/wmu" target="_blank">Web Management Unit</a></p>
			                            </div>
			                        </div>
			                    </div>
			                </div>
			            </div>
			        </div>