<div class="courses-area ptb-100 bg-f4f6f9">
            <div class="container">
                <div class="section-title">
                    <h2>Free Courses</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipiscing elit ut elit tellus luctus nec ullamcorper mattis</p>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="200" data-aos-once="true">
                        <div class="single-courses-card">
                            <div class="courses-img">
                                <a href="courses-details.html"><img src="assets/images/courses/courses-1.jpg" alt="Image"></a>
                            </div>
                            <div class="courses-content">
                                <div class="admin-profile">
                                    <img src="assets/images/courses/admin-1.jpg" alt="Image">
                                    <p>With <a href="courses-details.html">Jessica Hamson</a></p>
                                </div>
                                <a href="courses-details.html"><h3>Python Programming For Data Science</h3></a>
                                <div class="bottom-content">
                                    <ul class="d-flex justify-content-between">
                                        <li>
                                            <ul>
                                                <li><i class="flaticon-graduation"></i>321</li>
                                                <li><i class="flaticon-bubble-chat"></i>1.2k</li>
                                            </ul>
                                        </li>
                                        <li><a href="#">Free</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="400" data-aos-once="true">
                        <div class="single-courses-card">
                            <div class="courses-img">
                                <a href="courses-details.html"><img src="assets/images/courses/courses-2.jpg" alt="Image"></a>
                            </div>
                            <div class="courses-content">
                                <div class="admin-profile">
                                    <img src="assets/images/courses/admin-2.jpg" alt="Image">
                                    <p>With <a href="courses-details.html">Christoph Baldwin</a></p>
                                </div>
                                <a href="courses-details.html"><h3>Databases: Advanced Topics In SQL And Athers</h3></a>
                                <div class="bottom-content">
                                    <ul class="d-flex justify-content-between">
                                        <li>
                                            <ul>
                                                <li><i class="flaticon-graduation"></i>321</li>
                                                <li><i class="flaticon-bubble-chat"></i>1.2k</li>
                                            </ul>
                                        </li>
                                        <li><a href="#">Free</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="600" data-aos-once="true">
                        <div class="single-courses-card">
                            <div class="courses-img">
                                <a href="courses-details.html"><img src="assets/images/courses/courses-3.jpg" alt="Image"></a>
                            </div>
                            <div class="courses-content">
                                <div class="admin-profile">
                                    <img src="assets/images/courses/admin-3.jpg" alt="Image">
                                    <p>With <a href="courses-details.html">Morgen Matthias</a></p>
                                </div>
                                <a href="courses-details.html"><h3>Analyzing Data With MS Excel & Excel</h3></a>
                                <div class="bottom-content">
                                    <ul class="d-flex justify-content-between">
                                        <li>
                                            <ul>
                                                <li><i class="flaticon-graduation"></i>321</li>
                                                <li><i class="flaticon-bubble-chat"></i>1.2k</li>
                                            </ul>
                                        </li>
                                        <li><a href="#">Free</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="more-courses text-center">
                    <p>Select From Hundreds of Options <a href="courses.html" class="read-more-btn active">More on Courses <i class="flaticon-next"></i></a></p>
                </div>
            </div>
        </div>