	<div class="campus-life-area pt-100 pb-70">
	    <div class="container">
	        <div class="row justify-content-center">
	            <?php
                if (is_array($deans)) {
                    if (count($deans) > 0) {
                        for ($i = 0; $i < count($deans); $i++) {
                            $val = $deans[$i];
                            $fullName = $duration = $imgName = '';

                            if (isset($val['fullName'])) $fullName = $val['fullName'];
                            if (isset($val['duration'])) $duration = $val['duration'];
                            if (isset($val['imgName'])) $imgName = $val['imgName'];

                ?>
	                        <div class="col-lg-3 col-md-4">
	                            <div class="single-campus-card">
	                                <div class="img">
	                                    <img class="deans-img" src="assets/faculty/images/dean/<?=$imgName?>" width="100%" alt="<?=$fullName?>">
	                                </div>
	                                <div class="campus-content">
	                                    <h3 class="text-center"><?= $fullName ?></h3>
	                                    <p class="text-center"><span><?= $duration ?></span></p>
	                                </div>
	                            </div>
	                        </div>
	                    <?php   }
                    } else {
                        ?>

	                    <div class="alert alert-danger text-center">
	                        Please, pass a valid parameter with values.
	                    </div>

	                <?php }
                } else {
                    ?>
	                <div class="alert alert-danger text-center">
	                    Please, pass a valid parameter.
	                </div>
	            <?php
                }
                ?>
	        </div>
	    </div>
	</div>
	<!--End Campus Life Area-->