<div class="footer-area pt-100 pb-70">
				            <div class="container">
				                <div class="row">
				                    <div class="col-lg-4 col-sm-6">
				                        <div class="footer-logo-area">
				                            <a href="' .$this->baseUrl. '"><img src="assets/faculty/images/white-logo.png" alt="Image" class="footer-logo"></a>
				                            <p>'. ADDRESS. '.</p>
				                            <div class="contact-list">
				                                <ul>
				                                    <li><a href="tel:'. PHONE_NUM. '">'. PHONE_NUM. '
				                                    </a></li>
				                                    <li><a href="mailto:'. EMAIL. '">'. EMAIL. '</a></li>
				                                </ul>
				                            </div>
				                        </div>
				                    </div>
				                    <div class="col-lg-3 col-sm-6">
				                        <div class="footer-widjet">
				                            <h3>Facilities and Services</h3>
				                            <div class="list">
				                                <ul>
				                                    <li><a href="https://uhs.abu.edu.ng/" target="_blank">University Health Services</a></li>
				                                    <li><a href="https://abu.edu.ng/counselling-and-human-development" target="_blank">Counselling & Human Dev Centre</a></li>
				                                    <li><a href="https://abu.edu.ng/energy-bulk-metering-unit" target="_blank">Electricity Bulk Metering Unit</a></li>
				                                </ul>
				                            </div>
				                        </div>
				                    </div>
				                    <div class="col-lg-3 col-sm-6">
				                        <div class="footer-widjet">
				                            <h3>Campus Life</h3>
				                            <div class="list">
				                                <ul>
				                                    <li><a href="https://abu.edu.ng/coming-soon" target="_blank">Students Representative Council (SRC)</a></li>
				                                    <li><a href="https://portal.abu.edu.ng/" target="_blank">Students Campus Accomodation</a></li>
				                                    <li><a href="https://hotspot.abu.edu.ng/" target="_blank">ABU Free Wi-Fi Services</a></li>
				                                </ul>
				                            </div>
				                        </div>
				                    </div>
				                    <div class="col-lg-2 col-sm-6">
				                        <div class="footer-widjet">
				                            <h3>Academics</h3>
				                            <div class="list">
				                                <ul>
				                                    <li><a href="https://portal.abu.edu.ng" target="_blank">UG Student Portal</a></li>
				                                    <li><a href="https://spgs.abu.edu.ng" target="_blank">PG Portal</a></li>
				                                    <li><a href="https://library.abu.edu.ng/" target="_blank">Library</a></li>
				                                </ul>
				                            </div>
				                        </div>
				                    </div>
				                </div>
				                <div class="shape">
				                    <img src="assets/faculty/images/shape-1.png" alt="Image">
				                </div>
				            </div>
				        </div>