<div class="health-care-area ptb-100">
            <div class="container">
                <div class="section-title">
                    <h2>Health Care</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipiscing elit ut elit tellus luctus nec ullamcorper mattis </p>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="200" data-aos-once="true">
                        <div class="single-health-care-card">
                            <div class="img">
                                <a href="health-care-details.html"><img src="assets/images/health-care/health-care-1.jpg" alt="Image"></a>
                            </div>
                            <div class="health-care-content">
                                <a href="health-care-details.html"><h3>Happiness Begins With Good Health</h3></a>
                                <p>Lorem ipsum dolor sit amet con sec teturo adip iscing elit sed do eiusmod tempor insi didunt ut labore et dolore</p>
                                <a href="health-care.html" class="read-more-btn">Read More on healthcare<i class="flaticon-next"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="400" data-aos-once="true">
                        <div class="single-health-care-card">
                            <div class="img">
                                <a href="health-care-details.html"><img src="assets/images/health-care/health-care-2.jpg" alt="Image"></a>
                            </div>
                            <div class="health-care-content">
                                <a href="health-care-details.html"><h3>When Life Depends on Medical Technology</h3></a>
                                <p>Lorem ipsum dolor sit amet con sec teturo adip iscing elit sed do eiusmod tempor insi didunt ut labore et dolore</p>
                                <a href="health-care.html" class="read-more-btn">Read More on healthcare<i class="flaticon-next"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="600" data-aos-once="true">
                        <div class="single-health-care-card">
                            <div class="img">
                                <a href="health-care-details.html"><img src="assets/images/health-care/health-care-3.jpg" alt="Image"></a>
                            </div>
                            <div class="health-care-content">
                                <a href="health-care-details.html"><h3> Making A Meaningful Difference In Patients’ lives.</h3></a>
                                <p>Lorem ipsum dolor sit amet con sec teturo adip iscing elit sed do eiusmod tempor insi didunt ut labore et dolore</p>
                                <a href="health-care.html" class="read-more-btn">Read More on healthcare<i class="flaticon-next"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="more-health-care text-center">
                    <p>Select From Hundreds of Options. <a href="health-care.html" class="read-more-btn active">More on healthcare<i class="flaticon-next"></i></a></p>
                </div>
            </div>
        </div>