<div class="lates-news-area ptb-100">
            <div class="container">
                <div class="section-title">
                    <h2>Latest News</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipiscing elit ut elit tellus luctus nec ullamcorper mattis</p>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="200" data-aos-once="true">
                        <div class="single-news-card">
                            <div class="news-img">
                                <a href="news-details.html"><img src="assets/images/news/news-1.jpg" alt="Image"></a>
                            </div>
                            <div class="news-content">
                                <div class="list">
                                    <ul>
                                        <li><i class="flaticon-user"></i>By <a href="news-details.html">Admin</a></li>
                                        <li><i class="flaticon-tag"></i>Social Sciences</li>
                                    </ul>
                                </div>
                                <a href="news-details.html"><h3>Professor Tom Comments On The Volunteer B. Snack Brand</h3></a>
                                <a href="news-details.html" class="read-more-btn">Read More<i class="flaticon-next"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="400" data-aos-once="true">
                        <div class="single-news-card">
                            <div class="news-img">
                                <a href="news-details.html"><img src="assets/images/news/news-2.jpg" alt="Image"></a>
                            </div>
                            <div class="news-content">
                                <div class="list">
                                    <ul>
                                        <li><i class="flaticon-user"></i>By <a href="news-details.html">Admin</a></li>
                                        <li><i class="flaticon-tag"></i>Social Sciences</li>
                                    </ul>
                                </div>
                                <a href="news-details.html"><h3>How To Use Technology To Adapt Your Talent To The World</h3></a>
                                <a href="news-details.html" class="read-more-btn">Read More<i class="flaticon-next"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="1200" data-aos-delay="600" data-aos-once="true">
                        <div class="single-news-card">
                            <div class="news-img">
                                <a href="news-details.html"><img src="assets/images/news/news-3.jpg" alt="Image"></a>
                            </div>
                            <div class="news-content">
                                <div class="list">
                                    <ul>
                                        <li><i class="flaticon-user"></i>By <a href="news-details.html">Admin</a></li>
                                        <li><i class="flaticon-tag"></i>Social Sciences</li>
                                    </ul>
                                </div>
                                <a href="news-details.html"><h3>Here Are The Things To Look For When Selecting An Online Course</h3></a>
                                <a href="news-details.html" class="read-more-btn">Read More<i class="flaticon-next"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="more-latest-news text-center">
                    <p>Select From Hundreds of Options.<a href="latest-news.html" class="read-more-btn active"> More on News<i class="flaticon-next"></i></a></p>
                </div>
            </div>
        </div>