<div class="navbar-area nav-bg-1">
    <div class="mobile-responsive-nav">
        <div class="container">
            <div class="mobile-responsive-menu">
                <div class="logo">
                    <a href="index.html">
                        <img src="assets/faculty/images/logo.png" class="main-logo" lt="logo">
                        <img src="assets/faculty/images/white-logo.png" class="white-logo" alt="logo">
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="desktop-nav">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-md navbar-light">
                <a class="navbar-brand" href="/faculty">
                    <img src="assets/faculty/images/white-logo.png" alt="logo">
                </a>
                <div class="site-brand-name" style="padding-right:50px; border-right: 1px solid gray;">
                    <span style="color:#008753"><?=$qualifiedName?></span> <br />
                    <?=$instName?>
                </div>
                <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto">
                       <li class="nav-item">
			                                    <a href="/faculty" class="nav-link <?php echo $page=='home'?'active':''; ?>">Home</a>
			                                </li>
											
			                                <li class="nav-item">
			                                    <a href="#" class="nav-link dropdown-toggle <?php echo $page=='about'?'active':''; ?>">
			                                        About us            
			                                    </a>
			                                    <ul class="dropdown-menu">
			                                        <li class="nav-item">
			                                            <a href="/fac-history" class="nav-link  <?php echo $sub_page=='history'?'active':''; ?>">History</a>
			                                        </li>
			                                    </ul>
			                                </li>

			                                <li class="nav-item">
			                                    <a href="#" class="nav-link dropdown-toggle <?php echo $page=='org'?'active':''; ?>">
			                                        Organization            
			                                    </a>
			                                    <ul class="dropdown-menu">
			                                        <li class="nav-item">
			                                            <a href="/fac-deans" class="nav-link <?php echo $sub_page=='deans'?'active':''; ?>">Deans of Faculty</a>
			                                        </li>
			                                    </ul>
			                                </li>

			                                <li class="nav-item">
			                                    <a href="/fac-staff" class="nav-link <?php echo $page=='staff'?'active':''; ?>">staff</a>
			                                </li>

			                                <li class="nav-item">
			                                    <a href="#" class="nav-link dropdown-toggle">
			                                        Department            
			                                    </a>
												
			                                    <ul class="dropdown-menu">
												<?php $this->include("partials/faculty/_navbar--departments.phtml") ?>
			                                    </ul>
			                                </li>

			                                <li class="nav-item <?php echo $page=='contact'?'active':''; ?>">
			                                    <a href="/fac-contact" class="nav-link '.$contact.'">Contact Us</a>
			                                </li>
			                            </ul>

                    </ul>

                    <div class="others-options">
                        <div class="icon">
                            <i class="ri-menu-3-fill" data-bs-toggle="modal" data-bs-target="#sidebarModal"></i>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div class="others-option-for-responsive">
        <div class="container">
            <div class="dot-menu">
                <div class="inner">
                    <div class="icon">
                        <i class="ri-menu-3-fill" data-bs-toggle="modal" data-bs-target="#sidebarModal"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>