<div class="navbar-area nav-bg-1">
    <div class="mobile-responsive-nav">
        <div class="container">
            <div class="mobile-responsive-menu">
                <div class="logo">
                    <a href="index.html">
                        <img src="assets/faculty/images/logo.png" class="main-logo" lt="logo">
                        <img src="assets/faculty/images/white-logo.png" class="white-logo" alt="logo">
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="desktop-nav">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-md navbar-light">
                <a class="navbar-brand" href="index.html">
                    <img src="assets/faculty/images/white-logo.png" alt="logo">
                </a>
                <div class="site-brand-name" style="padding-right:50px; border-right: 1px solid gray;">
                    <span style="color:#008753"><?=$qualifiedName?></span> <br />
                    <?=$instName?>
                </div>
                <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto">
                       <li class="nav-item">
			                                    <a href="'.$this->baseUrl.'" class="nav-link '.$home.'">Home</a>
			                                </li>

			                                <li class="nav-item">
			                                    <a href="#" class="nav-link dropdown-toggle '.$aboutCont.'">
			                                        About us            
			                                    </a>
			                                    <ul class="dropdown-menu">
			                                        <li class="nav-item">
			                                            <a href="' .$this->baseUrl. 'history" class="nav-link ' .$about. '">History</a>
			                                        </li>
			                                    </ul>
			                                </li>

			                                <li class="nav-item">
			                                    <a href="#" class="nav-link dropdown-toggle '.$org.'">
			                                        Organization            
			                                    </a>
			                                    <ul class="dropdown-menu">
			                                        <li class="nav-item">
			                                            <a href="' .$this->baseUrl. 'deans" class="nav-link ' .$deans. '">Deans of Faculty</a>
			                                        </li>
			                                    </ul>
			                                </li>

			                                <li class="nav-item">
			                                    <a href="'.$this->baseUrl.'staff" class="nav-link '.$people.'">staff</a>
			                                </li>

			                                <li class="nav-item">
			                                    <a href="#" class="nav-link dropdown-toggle">
			                                        Department            
			                                    </a>
			                                    <ul class="dropdown-menu">
			                                        <li class="nav-item">
			                                            <a href="'.$this->baseUrl.'departments/biochemistry" target="new" class="nav-link" target="_blank">Biochemistry</a>
			                                        </li>
			                                        <li class="nav-item">
			                                            <a href="'.$this->baseUrl.'departments/biology" target="new" class="nav-link" target="_blank">Biology</a>
			                                        </li>
			                                        <li class="nav-item">
			                                            <a href="'.$this->baseUrl.'departments/botany" target="new" class="nav-link" target="_blank">Botany</a>
			                                        </li>
			                                        <li class="nav-item">
			                                            <a href="'.$this->baseUrl.'departments/microbiology" target="new" class="nav-link" target="_blank">Microbiology</a>
			                                        </li>
			                                        <li class="nav-item">
			                                            <a href="'.$this->baseUrl.'departments/zoology" target="new" class="nav-link" target="_blank">Zoology</a>
			                                        </li>
			                                    </ul>
			                                </li>

			                                <li class="nav-item">
			                                    <a href="'.$this->baseUrl.'contact-us" class="nav-link '.$contact.'">Contact Us</a>
			                                </li>
			                            </ul>

                    </ul>

                    <div class="others-options">
                        <div class="icon">
                            <i class="ri-menu-3-fill" data-bs-toggle="modal" data-bs-target="#sidebarModal"></i>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div class="others-option-for-responsive">
        <div class="container">
            <div class="dot-menu">
                <div class="inner">
                    <div class="icon">
                        <i class="ri-menu-3-fill" data-bs-toggle="modal" data-bs-target="#sidebarModal"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>