<div class="sidebarModal modal right fade" id="sidebarModal" tabindex="-1" role="dialog">
			            <div class="modal-dialog" role="document">
			                <div class="modal-content">
			                    <button type="button" class="close" data-bs-dismiss="modal"><i class="ri-close-line"></i></button>

			                    <div class="modal-body">
			                        <a href="' .$this->baseUrl. '">
			                            <img src="assets/faculty/images/logo.png" class="main-logo" alt="logo">
			                            <img src="assets/faculty/images/white-logo.png" class="white-logo" alt="logo">
			                        </a>
			                        <div class="sidebar-content">
			                            <h3>About Us</h3>
			                            <p>The Faculty of Science is located within the core of the Main Campus, Samaru. It was established at the founding of the Ahmadu Bello University in 1962. The Faculty started with six departments and has grown over the past fifty-three years into not only one of the largest faculties in the University with nine degree awarding departments, but also one of the largest faculties of science in any Nigerian University.</p>

			                            <div class="sidebar-btn">
			                                <a href="'.$this->baseUrl.'history" class="default-btn">Read more</a>
			                            </div>
			                        </div>
			                        <div class="sidebar-contact-info">
			                            <h3>Contact Information</h3>

			                            <ul class="info-list">
			                                <li><i class="ri-phone-fill"></i> <a href="tel:'. PHONE_NUM. '"> '. PHONE_NUM. '</a></li>
			                                
			                                <li><i class="ri-mail-line"></i><a href="mailto:'. EMAIL. '"> '. EMAIL. '</a></li>
			                                
			                                <li><i class="ri-global-line"></i><a href="'. WEBSITE. '"> '. WEBSITE. '</a></li>

			                                <li><i class="ri-map-pin-line"></i> '. ADDRESS. ' </li>
			                            </ul>
			                        </div>
			                       
			                    </div>
			                </div>
			            </div>
			        </div>