<div class="top-header-area">
			            <div class="container-fluid">
			                <div class="row align-items-center">
			                    <div class="col-lg-6 col-md-6">
			                        <!--div class="header-left-content">
			                            <p>
			                            <span class="icon">
                                            <i class="ri-phone-line"></i>
                                        </span>
			                            Call us on: '. PHONE_NUM. '
			                            &nbsp;&nbsp;
			                            <span class="icon">
                                            <i class="ri-mail-line"></i>
                                        </span>
			                            Email us at: ' .EMAIL. '</p>
			                        </div-->
			                    </div>
			                    <div class="col-lg-6 col-md-6">                                        
			                        <div class="header-right-content">
			                            <div class="list">
			                                <ul>
			                                    <li><a href="https://abu.edu.ng" target="_blank">ABU Home</a></li>
			                                    <li><a href="https://portal.abu.edu.ng" target="_blank">Student portal</a></li>
			                                    <li><a href="https://spgs.abu.edu.ng" target="_blank">SPGS</a></li>
			                                    <li><a href="https://moodle.abu.edu.ng" target="_blank">Moodle</a></li>
			                                    <li><a href="https://library.abu.edu.ng" target="_blank">Library</a></li>
			                                </ul>
			                            </div>
			                        </div>
			                    </div>
			                </div>
			            </div>
					</div>