<div class="campus-information-area pb-70" style="padding-top:90px">
			            <div class="container">
                            <!--div class=" row align-items-center"-->
			                <div class="row ">
			                    <div class="col-lg-6">
			                        <div class="campus-image">
			                            <img class="h-75" src="<?=$head_img_url?>" alt="<?=$headName?>" style="width: 100%;">
			                            <div class="text-center bg-white">
    			                            <h3 class="pt-1"><?=$headName?></h3>
    			                            <h5 class="text-muted"><?=$headTitle?>, <?=$qualifiedName?></h5>
    			                        </div>
			                        </div>
			                    </div>
			                    <div class="col-lg-6">
			                        <div class="campus-content style-2">
			                            <div class="campus-title">
			                                <h2>Welcome Message</h2>
                                            <?=$welcome_message?>
			                            </div>
			                            <a href="welcome-message" class="default-btn btn">Read more<i class="flaticon-next"></i></a>
			                        </div>
			                    </div>
			                </div>
			            </div>
			        </div>