<!DOCTYPE html>
<html lang="zxx">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--Bootstrap Css-->
        <link rel="stylesheet" href="assets/faculty/css/bootstrap.min.css">
        <!--Meanmenu.css-->
        <link rel="stylesheet" href="assets/faculty/css/meanmenu.css">
        <!--Owl carousel-->
        <link rel="stylesheet" href="assets/faculty/css/owl.carousel.min.css">
        <!--Owl Theme-->
        <link rel="stylesheet" href="assets/faculty/css/owl.theme.default.min.css">
        <!--Magnific-popup-->
        <link rel="stylesheet" href="assets/faculty/css/magnific-popup.css">
        <!--Flaticon-->
        <link rel="stylesheet" href="assets/faculty/css/flaticon.css">
        <!--Remixicon-->
        <link rel="stylesheet" href="assets/faculty/css/remixicon.css">
        <!--Odometer-->
        <link rel="stylesheet" href="assets/faculty/css/odometer.min.css">
        <!--Aos css-->
        <link rel="stylesheet" href="assets/faculty/css/aos.css">
        <!--Style css-->
        <link rel="stylesheet" href="assets/faculty/css/style.css">
        <!--Dark css-->
        <link rel="stylesheet" href="assets/faculty/css/dark.css">
        <!--Responsive css-->
        <link rel="stylesheet" href="assets/faculty/css/responsive.css">

        <link rel="icon" type="image/png" href="assets/faculty/images/favicon.png">
        <title><?php echo $vPage == 'index' ? 'Home | ': $title . ' | '; echo "$deptName  |  $instName" ;  ?></title>
    </head>
    <body>
        <!-- Start Preloader Area -->
        <?php $this->include("partials/faculty/_preloader.phtml") ?>
        <!-- End Preloader Area -->

        <!--Strat Top Header Area-->
        <?php $this->include("partials/faculty/_top--header.phtml") ?>
        <!--End Top Header Area-->
        
        <!-- Start Navbar Area --> 
        <?php $this->include("partials/faculty/_navbar.phtml") ?>
        <!-- End Navbar Area -->

        <!-- Sidebar Modal -->
        <?php $this->include("partials/faculty/_sidebar--modal.phtml") ?>
        <!-- End Sidebar Modal -->

         <!-- Specific page content goes here -->
        <div class="container-fluid">
         <?php $this->content(); ?>
        </div>
        <!-- End Content-->

        <!-- Start Welcome message -->
        <?php //$this->include("partials/faculty/_welcome--message.phtml") ?>
        <!-- End Welcome message -->

        <!--Start Banner Area-->
        
        <!--End Banner Area-->

        <!--Start Academic Area-->
        
        <!--End Academic Area-->

        <!--Start Campus Information-->
        
        <!--End Campus Information-->

        <!--Start Courses Area-->
        
        <!--End Courses Area-->

        <!--Start Campus Life Area-->
        
        <!--End Campus Life Area-->

        <!--Start Admisssion Area-->
        
        <!--End Admisssion Area-->

        <!--Start Health Care Area-->
        
        <!--End Health Care Area-->

        <!--Start Events Area-->
        
        <!--End Events Area-->

        <!--Start Podcasts Area-->
        
        <!--End Podcasts Area-->

        <!--Start Check Student Stories-->
        
        <!--End Check Student Stories-->

        <!--Start Lates News Area-->
        
        <!--End News Area-->

        <!--Start Footer Area-->
        <?php $this->include("partials/faculty/_footer.phtml") ?>
        
        <!--End Footer Area-->

        <!--Start Copyright Area-->
        <?php $this->include("partials/faculty/_copyright.phtml") ?>
        <!--End Copyright Area-->

        <!-- Start Go Top Area -->
        <?php $this->include("partials/faculty/_goto--top.phtml") ?>
        <!-- End Go Top Area -->
        
        <!-- Jquery js -->
        <script src="assets/faculty/js/jquery.min.js"></script>
        <!-- Bootstrap bundle js -->
        <script src="assets/faculty/js/bootstrap.bundle.min.js"></script>
        <!-- Meanmenu js -->
        <script src="assets/faculty/js/jquery.meanmenu.js"></script>
        <!-- Owl Carosel js -->
        <script src="assets/faculty/js/owl.carousel.min.js"></script>
        <!-- Owl Carosel Thumbs js -->
        <script src="assets/faculty/js/carousel-thumbs.min.js"></script>
        <!-- Magnific popup js -->
        <script src="assets/faculty/js/jquery.magnific-popup.js"></script>
        <!-- Aos js -->
        <script src="assets/faculty/js/aos.js"></script>
        <!-- Odometer js -->    
        <script src="assets/faculty/js/odometer.min.js"></script>
        <!-- Appear js -->  
        <script src="assets/faculty/js/appear.min.js"></script> 
        <!-- Form Validator js -->    
        <script src="assets/faculty/js/form-validator.min.js"></script>
        <!-- Contact Form Script js -->    
        <script src="assets/faculty/js/contact-form-script.js"></script>
        <!-- Ajaxchimp js -->    
        <script src="assets/faculty/js/ajaxchimp.min.js"></script>
        <!--Custom js-->
        <script src="assets/faculty/js/custom.js"></script>
    </body>
</html>