<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apple Your</title>
</head>
<body>

<?php $this->include("_about.phtml", ["name"=>"I am YUSUF"]) ?>
    <!-- Specific page content goes here -->
    <?php $this->content(); ?>
        <!-- Footer -->
    <?php $this->include("_love.phtml") ?>
</body>
</html>