<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Title -->
    <title><?php echo $vPage == 'index' ? 'Home | ': $title . ' | '; echo "$deptName  |  $instName" ;  ?></title>
</head>
<body>

<?php $this->include("partials/defaultConceptTest/_about.phtml", ["name"=>"I am YUSUF"]) ?>
    <!-- Specific page content goes here -->
    <?php $this->content(); ?>
        <!-- Footer -->
    <?php $this->include("partials/defaultConceptTest/_love.phtml") ?>
</body>
</html>