<div class="campus-information-area pb-70" style="padding-top:90px">
    <div class="container">
        <!--div class=" row align-items-center"-->
        <div class="row">
            <div class="col-lg-12">
                <div class="campus-content style-2">
                    <div class="campus-title">
                        <h2>About Us</h2>
                        <?= $welcome_message ?>
                    </div>
                    <div class="campus-title">
                        <h2>History</h2>
                        <?= $history ?>
                    </div>
                    <div class="campus-title">
                        <h2>Mission</h2>
                        <?= $mission ?>
                    </div>
                    <div class="campus-title">
                        <h2>Vision</h2>
                        <?= $vision ?>
                    </div>
                    <div class="campus-title">
                        <h2>Philosophy</h2>
                        <?= $philosophy ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>