<div class="campus-information-area pb-70 container" style="padding-top:90px">
    <div class="container">
        <!--div class=" row align-items-center"-->
        <div class="row">
            <div class="col-lg-12">
                <div class="campus-content style-2">
            
                    <div class="campus-title">
                        <h2>History</h2>
                        <?= $history ?>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>